version: '2'
services:
  blocklistform:
    image: icetail/blocklistform
    ports:
     - "80:80"
    depends_on:
    - "mysql"
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: db_blocklist
      MYSQL_PASSWORD: db_blocklist
      MYSQL_DATABASE: db_blocklist