version: '2'
services:
  blocklistform:
    build:
      context: .
      dockerfile: .
      ports:
        - "80:80"
      depends_on: 
        - "mysql"
    mysql:
      image: "mysql:5.7"
      environment: 
        DB_SERVER: db
        DB_USERNAME: dbuser
        DB_PASSWORD: dbpassword
        DB_NAME: company